export const accountList = [
  {
    username: "tom",
    password: "000000",
    phone: "13688888888",
    token: "token_tom",
  },
  {
    username: "jerry",
    password: "999999",
    phone: "13699999999",
    token: "token_jerry",
  },
];

export const orderList = [
  {
    BizType: "Vacation",
    OrderID: 21300536144,
    OrderName:
      "西安3日2晚跟团游·【风华秦韵 ·12人精致小团】【新春大促  立减400元/人】兵马俑+华清池+西安城墙+回民街&高家大院+大雁塔&大唐不夜城丨24小时专车接送·非遗体验《华州皮影+老腔》·赠送美食地图·通关文牒·讲解耳麦",
    OrderStatusCode: "VACATION_UNCOMMIT",
    OrderStatusName: "未提交",
    Currency: "CNY",
    OrderTotalPrice: 1960,
    BookingDate: "1676559828801",
    Passagers: ["习佳", "赵康"],
    ContactName: "赵康",
    ContactMobile: "187oClL8239",
    Longitude: 0,
    Latitude: 0,
    OrderType: "10000",
    IsFromCurrentUser: true,
    IsNeedBind: false,
    HotelOrderItems: [],
    TrainOrderItems: [],
    VacationOrderItems: [
      {
        ProductName:
          "西安3日2晚跟团游·【风华秦韵 ·12人精致小团】【新春大促  立减400元/人】兵马俑+华清池+西安城墙+回民街&高家大院+大雁塔&大唐不夜城丨24小时专车接送·非遗体验《华州皮影+老腔》·赠送美食地图·通关文牒·讲解耳麦",
        DepartureDate: "1676822400000",
        DepartureCity: "西安",
        EndDate: "1676995200000",
        ProductType: "9",
        ProductPattern: "1",
        OrderDbType: 30,
        DistributionChannel: "",
        SubOrderType: "0",
        SaleMode: "P",
        DepartureCityID: "10",
        ArrivalCityID: "10",
        ArrivalCity: "西安",
        IsPreSaleOrder: false,
        IsReserved: false,
        AdvanceBookingDays: 0,
      },
    ],
    PiaoOrderItems: [],
    FlightOrderItems: [],
    CarOrderItems: [],
    TuanOrderItems: [],
    TaxiOrderItems: [],
    DIYOrderItems: [],
    LipinOrderItems: [],
    OrderActions: [
      {
        ActionCode: "Detail",
        ActionName: "订单详情",
        ActionURLH5:
          "http://vacations.ctrip.com/tour/order_detail/order_details?orderId=304233337",
        ActionType: "Link",
        ActionRank: 0,
        ActionStyle: "Style1",
        StandardCode: "Detail",
        LinkType: "Default",
        H5Title: "",
        Extension: "",
        UrlSource: "",
      },
      {
        ActionCode: "PkgDetail",
        ActionName: "产品详情",
        ActionURLH5: "http://vacations.ctrip.com/tour/detail/p28725364s10.html",
        ActionType: "Link",
        ActionRank: 50,
        ActionStyle: "Style1",
        StandardCode: "ProductUrl",
        LinkType: "Default",
        H5Title: "",
        Extension: "",
        UrlSource: "",
      },
    ],
    CruiseOrderItems: [],
    QicheOrderItems: [],
    TopShopOrderItems: [],
    VisaOrderItems: [],
    ActivityOrderItems: [],
    VacationInsuranceOrderItems: [],
    AirportBusOrderItems: [],
    HHTravelOrderItems: [],
    DinnerOrderItems: [],
    GolfOrderItems: [],
    GlobalBuyOrderItems: [],
    MallOrderItems: [],
    DepositOrderItems: [],
    CustomizedOrderItems: [],
    ShipOrderItems: [],
    ExchangeOrderItem: [],
    MeetingOrderItem: [],
    LoungeOrderItem: [],
    FishTripOrderItem: [],
    GlobalBuyVoucherItems: [],
    FinInsOrderItems: [],
    MiceOrderItems: [],
    CrowdFundingOrderItems: [],
    GuiderOrderItems: [],
    PreSaleOrderItems: [],
    TranslationOrderItems: [],
    LipinSurpriseOrderItems: [],
    DriverOrderItems: [],
    FlightXOrderItems: [],
    ParentOrderID: 0,
    OrderRecommendations: [],
    BagOrderItems: [],
    ViewType: "Vacation",
    HealthOrderItems: [],
    CreditOrderItems: [],
    SportOrderItems: [],
    OneOrderItems: [],
    TotalQuantity: 0,
    FlightXOrderItemInfos: [],
    UsedTime: "1676822400000",
    OrderAssitants: [],
    TravelATOrderItems: [],
    YachtOrderItems: [],
    RailsIntlOrderItems: [],
    GsFoodOrderItems: [],
    CashPassportOrderItems: [],
    IsShared: false,
    CountryCode: "86",
    IsNotTravel: false,
    IsTraveled: false,
    IsOthers: false,
    MktAosOrderItems: [],
    GsFoodQueueOrderItems: [],
    FlightCorOrderItems: [],
    IsOnlineOnlyShowOrder: false,
    IsBasedQueryLocaleOnlyShowOrder: false,
    OiOrderType: "10000",
    LocalGuideOrderItems: [],
    IsSupportCurrentChannel: true,
    IsMultiResource: false,
    CommonOrderItems: [],
    OrderNoteInfo: [],
    OrderAmount: {
      PayInfos: ["总额 <b>[CNY]1960<b>"],
      RefundInfos: [],
      Validity: true,
    },
    TotalAmount: 1960,
  },
  {
    BizType: "Vacation",
    OrderID: 21408549436,
    OrderName:
      "厦门+鼓浪屿+福建土楼+漳州+泉州6日5晚跟团游·【鹭岛环游+世遗土楼+粉色梦境火山岛+探秘泉州古寺】精选市区优质酒店+一晚岛上 经典日光岩&沙坡尾&火山岛&云水谣&开元寺 『厦门境内15人精品小团』赠限时旅拍 B线",
    OrderStatusCode: "VACATION_UNCOMMIT",
    OrderStatusName: "未提交",
    Currency: "CNY",
    OrderTotalPrice: 7814,
    BookingDate: "1676906404886",
    Passagers: ["习佳", "赵康"],
    ContactName: "赵康",
    ContactMobile: "187oClL8239",
    Longitude: 0,
    Latitude: 0,
    OrderType: "10000",
    IsFromCurrentUser: true,
    IsNeedBind: false,
    HotelOrderItems: [],
    TrainOrderItems: [],
    VacationOrderItems: [
      {
        ProductName:
          "厦门+鼓浪屿+福建土楼+漳州+泉州6日5晚跟团游·【鹭岛环游+世遗土楼+粉色梦境火山岛+探秘泉州古寺】精选市区优质酒店+一晚岛上 经典日光岩&沙坡尾&火山岛&云水谣&开元寺 『厦门境内15人精品小团』赠限时旅拍 B线",
        DepartureDate: "1677081600000",
        DepartureCity: "西安",
        EndDate: "1677513600000",
        ProductType: "10",
        ProductPattern: "1",
        OrderDbType: 30,
        DistributionChannel: "",
        SubOrderType: "0",
        SaleMode: "P",
        DepartureCityID: "10",
        ArrivalCityID: "25",
        ArrivalCity: "厦门",
        IsPreSaleOrder: false,
        IsReserved: false,
        AdvanceBookingDays: 0,
      },
    ],
    PiaoOrderItems: [],
    FlightOrderItems: [],
    CarOrderItems: [],
    TuanOrderItems: [],
    TaxiOrderItems: [],
    DIYOrderItems: [],
    LipinOrderItems: [],
    OrderActions: [
      {
        ActionCode: "Detail",
        ActionName: "订单详情",
        ActionURLH5:
          "http://vacations.ctrip.com/tour/order_detail/order_details?orderId=304272011",
        ActionType: "Link",
        ActionRank: 0,
        ActionStyle: "Style1",
        StandardCode: "Detail",
        LinkType: "Default",
        H5Title: "",
        Extension: "",
        UrlSource: "",
      },
      {
        ActionCode: "PkgDetail",
        ActionName: "产品详情",
        ActionURLH5: "http://vacations.ctrip.com/tour/detail/p29347924s10.html",
        ActionType: "Link",
        ActionRank: 50,
        ActionStyle: "Style1",
        StandardCode: "ProductUrl",
        LinkType: "Default",
        H5Title: "",
        Extension: "",
        UrlSource: "",
      },
    ],
    CruiseOrderItems: [],
    QicheOrderItems: [],
    TopShopOrderItems: [],
    VisaOrderItems: [],
    ActivityOrderItems: [],
    VacationInsuranceOrderItems: [],
    AirportBusOrderItems: [],
    HHTravelOrderItems: [],
    DinnerOrderItems: [],
    GolfOrderItems: [],
    GlobalBuyOrderItems: [],
    MallOrderItems: [],
    DepositOrderItems: [],
    CustomizedOrderItems: [],
    ShipOrderItems: [],
    ExchangeOrderItem: [],
    MeetingOrderItem: [],
    LoungeOrderItem: [],
    FishTripOrderItem: [],
    GlobalBuyVoucherItems: [],
    FinInsOrderItems: [],
    MiceOrderItems: [],
    CrowdFundingOrderItems: [],
    GuiderOrderItems: [],
    PreSaleOrderItems: [],
    TranslationOrderItems: [],
    LipinSurpriseOrderItems: [],
    DriverOrderItems: [],
    FlightXOrderItems: [],
    ParentOrderID: 0,
    OrderRecommendations: [],
    BagOrderItems: [],
    ViewType: "Vacation",
    HealthOrderItems: [],
    CreditOrderItems: [],
    SportOrderItems: [],
    OneOrderItems: [],
    TotalQuantity: 0,
    FlightXOrderItemInfos: [],
    UsedTime: "1677081600000",
    OrderAssitants: [],
    TravelATOrderItems: [],
    YachtOrderItems: [],
    RailsIntlOrderItems: [],
    GsFoodOrderItems: [],
    CashPassportOrderItems: [],
    IsShared: false,
    CountryCode: "86",
    IsNotTravel: false,
    IsTraveled: false,
    IsOthers: false,
    MktAosOrderItems: [],
    GsFoodQueueOrderItems: [],
    FlightCorOrderItems: [],
    IsOnlineOnlyShowOrder: false,
    IsBasedQueryLocaleOnlyShowOrder: false,
    OiOrderType: "10000",
    LocalGuideOrderItems: [],
    IsSupportCurrentChannel: true,
    IsMultiResource: false,
    CommonOrderItems: [],
    OrderNoteInfo: [],
    OrderAmount: {
      PayInfos: ["总额 <b>[CNY]7814<b>"],
      RefundInfos: [],
      Validity: true,
    },
    TotalAmount: 7814,
  },
];
